ayosite/ayosite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('website.urls')),
    path('tinymce', include('tinymce.urls')),
    path('admin/', admin.site.urls), 
    path('accounts/', include('allauth.urls')), ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ayosite/website/urls.py
from django.urls import path
from . import views

app_name = 'website'

urlpatterns = [
    path('', views.home, name = 'home'),
    path('merch', views.shop, name = 'merchandise'),
    path('merch/<slug>', views.shop, name = 'merchandise_by_category'),
    path('room', views.room, name = "room"),
    path('contact_info', views.contact, name = 'shop'),
    path('checkout-mailing', views.CheckoutView.as_view(), name = "checkout"),
    path('checkout-payment/<payment_option>', views.PaymentView.as_view(), name = "payment"),
    path('Order_Summary', views.order_sum, name = "order_summary"),
    path('product_detail/<slug:slug>', views.product_detail, name='product_detail'),
    path('product_list', views.product_list, name='product_list'),
    path('product_list/<slug:slug>', views.product_list, name='product_list_by_category'),
    path('add_to_cart/<slug:slug>', views.add_to_cart, name = 'add_to_cart'),
    path('remove_from_cart/<slug:slug>', views.remove_from_cart, name = 'remove_from_cart') ]

ayosite/cart/models.py
from django.db import models
# from ayosite.website.models import Product

# class CartItem(models.Model):
#     cart_id = models.CharField(max_length=50)
#     date_added = models.DateTimeField(auto_now_add=True)
#     quantity = models.IntegerField(default=1)
#     product = models.ForeignKey('catalog.Product', unique=False, on_delete=models.CASCADE)

#     class Meta:
#         db_table = 'cart_items'
#         ordering = ['date_added']

#     def total(self):
#         return self.quantity * self.product.price

#     def name(self):
#         return self.product.name

#     def price(self):
#         return self.product.price

#     def get_absolute_url(self):
#         return self.product.get_absolute_url()

#     def augment_quantity(self, quantity):
#         self.quantity = self.quantity + int(quantity)
#         self.save()

ayosite/cart/views.py
from django.shortcuts import render

# Create your views here.

ayosite/templates/base.html
{% load static %}
<!DOCTYPE html>

<html lang="en" dir="ltr">
  <head>
    <title>Ayo's Site</title>
    <!--
      <link rel="shortcut icon" href="http://www.brianshim.com/webtricks/wp-content/uploads/2012/11/stars_favicon.png" type="image/x-icon" />
    -->
    <link rel="shortcut icon" href="background.png" type="image/x-icon" />
    <link rel="stylesheet" href="{% static 'css/website.css' %}">
    <!--Load icon Lib-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <meta charset="utf-8">
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>


    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="{% static 'css/mdb.css' %}" rel="stylesheet">
    <!-- Your custom styles (optional) -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
  </head>



  <!-- Navbar -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-light orangered scrolling-navbar">
      <div class="container">
  
  
        <!-- Collapse -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
  
        <!-- Links -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
  
          <!-- Left -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link waves-effect" href="/">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link waves-effect" href="/room">Room</a>
            </li>
            <li class="nav-item">
              <a class="nav-link waves-effect" href="/merch">Merch</a>
            </li>
            <li class="nav-item">
              <a class="nav-link waves-effect" href="/product_list" >Product List</a>
            </li>
          </ul>
  
          <!-- Right -->
          <ul class="navbar-nav nav-flex-icons">
            <!--Item Cart-->
            <li class="nav-item">
              <a href="{% url 'website:order_summary' %}"class="nav-link waves-effect">
                <span class="badge red z-depth-1 mr-1">{{ orders }}</span>
                <i class="fas fa-shopping-cart"></i>
                <span class="clearfix d-none d-sm-inline-block">Cart </span>
              </a>
            </li>
            <!--/.Item Cart-->

            <!--SignIn/Out-->
            <li class="nav-item">
              <a href="https://twitter.com/MDBootstrap" class="nav-link waves-effect" target="_blank">
                <i class="fas fa-sign-in-alt"></i>
                {% if user.is_authenticated %}
                  Sign Out
                {% else %}
                  Login/Sign Up
                {% endif %}
              </a>
            </li>
            <!--/.SignIn-->
            
            <!--Logo-->
            <li class="nav-item">
                <a href="https://twitter.com/MDBootstrap" class="nav-link waves-effect" target="_blank">
                  <i class="fas fa-user-circle"></i>
                </a>
            </li>

          </ul>
  
        </div>
  
      </div>
    </nav>
  

  
  
    </div>
    <div style="padding-bottom:70px"></div>
    <!--Messages-->
    {% if messages %}
      {% for message in messages %}
      <div class="alert alert-{{ message.tags }}" role="alert">{{ message }}</div>
      {% endfor %}
    {% endif %}
    <!--/Messages-->
    <div class="main-content">
        {% block content %}
        {% endblock content %}
    </div>
    </body>
</html>

ayosite/templates/cart.html
{% extends 'base.html' %}

{% block content %}
     <h1>Cart Page Here</h1>
     Cart item count: {{ cart_item_count }}
{% endblock %}

ayosite/templates/checkout-mailing.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Material Design Bootstrap</title>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'css/mdb.min.css'%}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'css/style.min.css'%}" rel="stylesheet">
</head>

<body class="grey lighten-3">
  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container wow fadeIn">

      <!-- Heading -->
      <h2 class="my-5 h2 text-center">Checkout form</h2>

      <!--Grid row-->
      <div class="row">

        <!--Grid column-->
        <div class="col-md-8 mb-4">

          <!--Card-->
          <div class="card">

            <form action="">
              {% csrf_token %}
              {{ form|crispy }}
              <button class="btn btn-primary" type = 'submit'>Checkout</button>
            </form>

            <!--Card content-->
            <form class="card-body">

              <!--Grid row-->
              <div class="row">

                <!--Grid column-->
                <div class="col-md-6 mb-2">

                  <!--firstName-->
                  <div class="md-form ">
                    <input type="text" id="firstName" class="form-control">
                    <label for="firstName" class  ="">First name</label>
                  </div>

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-md-6 mb-2">

                  <!--lastName-->
                  <div class="md-form">
                    <input type="text" id="lastName" class="form-control">
                    <label for="lastName" class="">Last name</label>
                  </div>

                </div>
                <!--Grid column-->

              </div>
              <!--Grid row-->


              <!--email-->
              <div class="md-form mb-5">
                <input type="text" id="email" class="form-control" placeholder="youremail@example.com">
                {{ form.street_address }}
                <h5 for="email" class="">Email (optional)</h5>
              </div>

              <!--address-->
              <div class="md-form mb-5">
                <input type="text" id="address" class="form-control" placeholder="1234 Main St">
                <h5 for="address" class="">Address</h5>
              </div>

              <!--address-2-->
              <div class="md-form mb-5">
                <input type="text" id="address-2" class="form-control" placeholder="Apartment or suite">
                <h5 for="address-2" class="">Address 2 (optional)</h5>
              </div>

              <!--Grid row-->
              <div class="row">

                <!--Grid column-->
                <div class="col-lg-4 col-md-12 mb-4">

                  <label for="country">Country</label>
                  <select class="custom-select d-block w-100" id="country" required>
                    <option value="">Choose...</option>
                    <option>United States</option>
                  </select>
                  {{ form.country }}
                  <div class="invalid-feedback">
                    Please select a valid country.
                  </div>

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-lg-4 col-md-6 mb-4">

                  <label for="state">State</label>
                  <select class="custom-select d-block w-100" id="state" required>
                    <option value="">Choose...</option>
                    <option>California</option>
                  </select>
                  <div class="invalid-feedback">
                    Please provide a valid state.
                  </div>

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-lg-4 col-md-6 mb-4">

                  <label for="zip">Zip</label>
                  {{ form.zip }}
                  <div class="invalid-feedback">
                    Zip code required.
                  </div>

                </div>
                <!--Grid column-->

              </div>
              <!--Grid row-->

              <hr>

              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" id="same-address">
                <label class="custom-control-label" for="same-address">Shipping address is the same as my billing address</label>
              </div>
              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" id="save-info">
                <label class="custom-control-label" for="save-info">Save this information for next time</label>
              </div>

              <hr>

              <div class="d-block my-3">
                <div class="custom-control custom-radio">
                  <input id="credit" name="paymentMethod" type="radio" class="custom-control-input" checked required>
                  <label class="custom-control-label" for="credit">Credit card</label>
                </div>
                <div class="custom-control custom-radio">
                  <input id="debit" name="paymentMethod" type="radio" class="custom-control-input" required>
                  <label class="custom-control-label" for="debit">Debit card</label>
                </div>
                <div class="custom-control custom-radio">
                  <input id="paypal" name="paymentMethod" type="radio" class="custom-control-input" required>
                  <label class="custom-control-label" for="paypal">Paypal</label>
                </div>
              </div>

              <hr class="mb-4">
              <form action="{% static url 'website:payment' %}">
                <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>
              </form>
            </form>

          </div>
          <!--/.Card-->

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-4 mb-4">

          <!-- Heading -->
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Your cart</span>
            <span class="badge badge-secondary badge-pill">3</span>
          </h4>

          <!-- Cart -->
          <ul class="list-group mb-3 z-depth-1">
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Product name</h6>
                <small class="text-muted">Brief description</small>
              </div>
              <span class="text-muted">$12</span>
            </li>
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Second product</h6>
                <small class="text-muted">Brief description</small>
              </div>
              <span class="text-muted">$8</span>
            </li>
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Third item</h6>
                <small class="text-muted">Brief description</small>
              </div>
              <span class="text-muted">$5</span>
            </li>
            <li class="list-group-item d-flex justify-content-between bg-light">
              <div class="text-success">
                <h6 class="my-0">Promo code</h6>
                <small>EXAMPLECODE</small>
              </div>
              <span class="text-success">-$5</span>
            </li>
            <li class="list-group-item d-flex justify-content-between">
              <span>Total (USD)</span>
              <strong>$20</strong>
            </li>
          </ul>
          <!-- Cart -->

          <!-- Promo code -->
          <form class="card p-2">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Promo code" aria-label="Recipient's username" aria-describedby="basic-addon2">
              <div class="input-group-append">
                <button class="btn btn-secondary btn-md waves-effect m-0" type="button">Redeem</button>
              </div>
            </div>
          </form>
          <!-- Promo code -->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->

  <!--Footer-->
  <footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <!--Call to action-->
    <div class="pt-4">
      <a class="btn btn-outline-white" href="https://mdbootstrap.com/docs/jquery/getting-started/download/" target="_blank" role="button">Download MDB
        <i class="fas fa-download ml-2"></i>
      </a>
      <a class="btn btn-outline-white" href="https://mdbootstrap.com/education/bootstrap/" target="_blank" role="button">Start free tutorial
        <i class="fas fa-graduation-cap ml-2"></i>
      </a>
    </div>
    <!--/.Call to action-->

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="https://www.facebook.com/mdbootstrap" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="https://twitter.com/MDBootstrap" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
        <i class="fab fa-google-plus-g mr-3"></i>
      </a>

      <a href="https://dribbble.com/mdbootstrap" target="_blank">
        <i class="fab fa-dribbble mr-3"></i>
      </a>

      <a href="https://pinterest.com/mdbootstrap" target="_blank">
        <i class="fab fa-pinterest mr-3"></i>
      </a>

      <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>

      <a href="http://codepen.io/mdbootstrap/" target="_blank">
        <i class="fab fa-codepen mr-3"></i>
      </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2019 Copyright:
      <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> MDBootstrap.com </a>
    </div>
    <!--/.Copyright-->

  </footer>
  <!--/.Footer-->

  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="js/jquery-3.4.1.min.js"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="js/popper.min.js"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="js/bootstrap.min.js"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="js/mdb.min.js"></script>
  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();
  </script>
</body>

</html>
{% endblock %}

ayosite/templates/order-summary.html
{% extends 'base.html' %}
{% block content %}
<div class="card">
    <h1>Cart Summary: </h1>
    
    {% for order_item in order_items %}
        
        <h4>{{ order_item }}</h4>
        <img src="{{ order_item.item.image.url }}" style="width: 300px; height: auto;">
    {% endfor %}
    <!-- Item Title/Name | quantity | item price | total item price (w/ quantity) -->
    <!-- Continue shopping button | proceed to checkout button -->
    <form action="{% url 'website:checkout' %}">
            <button>Proceed to Checkout</button>
    </form>
</div>
{% endblock %}

ayosite/templates/shop.html
{% extends "base.html" %}
{% load static %}


{% block content %}

{% load static %}
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Material Design Bootstrap</title>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'css/mdb.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
 
    <!-- 
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"> 
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.min.css' %}" rel="stylesheet"> 
    -->

  <style type="text/css">

    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>

<body>
   <!--Carousel Wrapper-->
   <div id="carousel-example-1z" class="carousel slide carousel-fade pt-4" data-ride="carousel">

    <!--Slides-->
    <div class="carousel-inner" role="listbox">

      <!--First slide/Poster-->
      <div class="carousel-item active">
        <div class="view" style="background-image: url('static/Ekko/sandstorm.jpg'); background-repeat: no-repeat; background-size: cover;">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Ayo can say a motto here</strong>
              </h1>

              <p>
                <strong>Friends, this is the beginning</strong>
              </p>

              <p class="mb-4 d-none d-md-block">
                <strong>The circumstances of one's birth are irrelivant. It is what one does with the
                    their life that determines it's worth.
                </strong>
              </p>
              <!-- Video Wrapper -->
              <div class="video-styling">        
                <div class="video-wrapper">  
                  <iframe class="video" src="http://www.youtube.com/embed/W7qWa52k-nE"
                  width="560" height="315" align="middle" frameborder="0" allowfullscreen>
                </iframe>
                </div>
              </div >
              <a target="_blank" href="https://mdbootstrap.com/education/bootstrap/" class="btn btn-outline-white btn-lg"> 
                <!-- <i class="fas fa-video"></i> -->
                <i class="fas fa-play"></i>
                Watch now
              </a>
            </div>
            
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/First slide-->

    </div>
    <!--/.Slides-->
</div>

  <!--Main layout-->
  
  <main>
    <div class="container">

      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Categories:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'website:merchandise' %}">All
                  <span class="sr-only">(current)</span>
              </a>
            </li>

            {% for c in categories %}
              <li class="nav-item" {% if category.slug == c.slug %} class="active"{% endif %}>
                  <a class="nav-link" href="{{ c.get_absolute_url }}">{{ c.name }}</a>
              </li>
            {% endfor %}
          </ul>
          <!-- Links -->

          <form class="form-inline">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

      <!--Section: Products v.3-->
      <section class="text-center mb-4">
        <!--Grid row-->
        <div class="row" style="margin-top: 6%">
      
        <!-- Product list Image & link -->
        <div class="col-md-200 blog-main">  
              <div class="row">
                  {% for product in products %}
                    <div class="card text-center m-3">  
                              <a href="{{ product.get_absolute_url }}">
                                  <img class=mt-1 src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'img/default.jpg' %} {% endif %}" alt="..." style="height: 230px; width: auto">
                              </a>
                              <div class="caption">
                                  <h3 class="text-center dark-grey-text">
                                      <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                                  </h3>
                                  <p class="text-center font-weight-bold blue-text">USDA. ${{ product.price }}</p>
                              </div>
                    </div>
                  {% endfor %}
              </div>
        </div>

        
      </section>
      <!--Section: Products v.3-->



    </div>
  </main>
  <!--Main layout-->

  <!--Footer-->
  <footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="https://www.facebook.com/mdbootstrap" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="https://twitter.com/MDBootstrap" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
        <i class="fab fa-google-plus-g mr-3"></i>
      </a>

      <a href="https://dribbble.com/mdbootstrap" target="_blank">
        <i class="fab fa-dribbble mr-3"></i>
      </a>

      <a href="https://pinterest.com/mdbootstrap" target="_blank">
        <i class="fab fa-pinterest mr-3"></i>
      </a>

      <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>

      <a href="http://codepen.io/mdbootstrap/" target="_blank">
        <i class="fab fa-codepen mr-3"></i>
      </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2019 Copyright:
      <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> MDBootstrap.com </a>
    </div>
    <!--/.Copyright-->

  </footer>
  <!--/.Footer-->

  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="js/jquery-3.4.1.min.js"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="js/popper.min.js"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="js/bootstrap.min.js"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="js/mdb.min.js"></script>
  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();

  </script>
</body>

{% endblock content %}

ayosite/templates/web_practice_1.html
{% extends 'base.html' %}
{% block content %}
{% load static %}


<h1>Hello {{name}}</h1>

<!-- 
form action = "<function name from views>"
input type=submit, requests the function from views with
the name provided from action in the form field
-->
<form action = "add" method = 'post'>

<!-- 
For post requests, you must have a csrf_token 
sent for security verification (the one Django provides)
-->  
{% csrf_token %}

  enter 1st number: <input type="text" name="num_1" ><br>
  enter 1st number: <input type="text" name="num_2" ><br>
  <input type="submit">
 
</form>

<!-- <div>
  {% if not context %}
    Shit, nothin
  {% else %}  
    <title>{{ context.categories|length }}</title>
    <title>{{ context.products.0.name }}</title>
  {% endif %}
</div> -->

{% block title %}

{% if category %}{{ category.name }} {% else %} Products {% endif %}
{% endblock %}

   <div class="container-fluid">
      <div class="row" style="margin-top: 6%">

        <div class="col-sm-8 blog-main">

          <div class="blog-post">
              <div class="row">
                  {% for product in products %}
                      <div class="col-md-4">
                        <div class="thumbnail">
                            <a href="{{ product.get_absolute_url }}">
                                <img src="{% if product.image %} {{ product.image.url }} {% else %} {% static 'Ekko/project.jpg' %} {% endif %}" alt="..." style="height: 130px; width: auto">
                            </a>
                            <div class="caption">
                                <h3 class="text-center">
                                    <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                                </h3>
                                <p class="text-center">Kshs. {{ product.price }}</p>
                            </div>
                        </div>
                      </div>
                  {% endfor %}
              </div>


          </div><!-- /.blog-post -->

        </div><!-- /.blog-main -->

        <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
          <div class="sidebar-module">
            <ol class="list-unstyled">
              <li {% if not category %} class="active"{% endif %}><a href="{% url 'website:product_list' %}">All</a></li>
            {% for c in categories %}

              <li {% if category.slug == c.slug %} class="active"{% endif %}>
                  <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
              </li>
            {% endfor %}
            </ol>
          </div>
        </div><!-- /.blog-sidebar -->

      </div><!-- /.row -->

    </div><!-- /.container -->

{% endblock %}